language: ruby

rvm: 
  - 2.2.0

sudo: required

dist: trusty

services:
  - docker

install:
  - sudo apt-get -y update
  - sudo apt-get -y install apparmor-utils
  - sudo aa-complain /etc/apparmor.d/docker

script:
  - docker info
  - docker version
  - df -kh
  - docker pull redis
  - docker run -d redis
  - docker ps
  - docker inspect $(docker ps -q)
  - docker inspect $(docker ps -q) | grep '"Pid"' 
  - docker inspect $(docker ps -q) | grep '"Pid"' | cut -d ':' -f 2 
  - docker inspect $(docker ps -q) | grep '"Pid"' | cut -d ':' -f 2 | tr -d ',' 
  - docker inspect $(docker ps -q) | grep '"Pid"' | cut -d ':' -f 2 | tr -d ',' | xargs kill
  - docker ps

