language: ruby

sudo: required

dist: trusty

env:
  matrix:
    - SUITE=containers
    - SUITE=images
    - SUITE=docker-misc
    - SUITE=git

script:
  - docker info
  - docker version
  - df -kh
  - bundle install
  - bundle exec rspec

rvm: 
  - 2.2.0
